### ISSUE TITLE
code-review doesn't notify Phabricator when try jobs are done

### ISSUE THREAD

**Issue by abpostelnicu** [mozilla/code-review#1170]
For a while now this intermitent problem arise that code-review events doesn't notify phabricator when try jobs are finished.

**Comment by abpostelnicu** [comment]
Update on this issue, I think the problem arises from libmozevent where we handle the connection with Redis server and the auth message that we send is incompatible with the Redis version that we use.

`
    auth_response = await self.read_response()
  File "/usr/local/lib/python3.9/site-packages/aioredis-2.0.0-py3.9.egg/aioredis/connection.py", line 726, in on_connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioredis-2.0.0-py3.9.egg/aioredis/connection.py", line 868, in read_response
During handling of the above exception, another exception occurred:
aioredis.exceptions.AuthenticationWrongNumberOfArgsError: wrong number of arguments for 'auth' command
    raise response from None
`

**Comment by abpostelnicu** [comment]
Something strange happened on Heroku during the last update, the connection string has been upgraded to standard redis-server > 6.0.0 but the version we have is 4.0.14.
