### ISSUE TITLE
try-comm-central code-review results not reported

### ISSUE THREAD

**Issue by jfx2006** [mozilla/code-review#2042]
It looks like the bot needs to know about the new comm-unified repository.

https://firefox-ci-tc.services.mozilla.com/tasks/ChccDnINRpWxOCdRPstHdg/runs/0/logs/public/logs/live.log

```
2024-01-16 19:04:47.000265 [WARNING ] Backend rejected the payload: b'{"base_repository":["Object with url=https://hg.mozilla.org/comm-unified does not exist."]}'
2024-01-16 19:04:47.000275 [ERROR   ] Static analysis failure | extra={'revision': PHID-DIFF-jonkpeqnid5d46vgdawy, 'error': AssertionError('Stopping early because revision could not be created nor retrieved from the backend')
```

COMM_BASE_REPOSITORY is now set to use https://hg.mozilla.org/comm-unified.

**Comment by marco-c** [comment]
Here's the current config:
```
    - checkout: robust
      try_url: ssh://hg.mozilla.org/try-comm-central
      try_mode: json
      try_name: try-comm-central
      name: comm-central
      ssh_user: reviewbot
      url: https://hg.mozilla.org/comm-central
      decision_env_revision: COMM_HEAD_REV
      decision_env_repository: COMM_HEAD_REPOSITORY
      decision_env_prefix: COMM
```

Should we only change https://hg.mozilla.org/comm-central to https://hg.mozilla.org/comm-unified?

**Comment by marco-c** [comment]
Done, we should see it working after the next restart of the service.

**Comment by marco-c** [comment]
@jfx2006 is it working now?

**Comment by jfx2006** [comment]
As of earlier today it's not working.

If I query the backend I don't see comm-unified. https://api.code-review.moz.tools/v1/repository/

**Comment by coreycb** [comment]
Hey @marco-c Could you take a look at this again? It seems it didn't get resolved.

**Comment by marco-c** [comment]
@coreycb we're working on a few improvements for the bot, we will investigate this again soon.

**Comment by marco-c** [comment]
I see the following in the logs:
```
Oct 29 22:26:24 [34.19.26.8](https://my.papertrailapp.com/systems/14229533590/events?focus=1788046735835279360&selected=1788046735835279360) [code-review/production/bot](https://my.papertrailapp.com/events?q=program%3Acode-review%2Fproduction%2Fbot&focus=1788046735835279360&selected=1788046735835279360) 2024-10-29 22:26:24 backend.py: [warning  ] Backend rejected the payload: b'{"base_repository":["Object with url=https://hg.mozilla.org/comm-unified does not exist."]}'
```

**Comment by marco-c** [comment]
We likely need to add the repo to the DB, just like #985 (and we should finally document this better, see #988).

**Comment by marco-c** [comment]
With #2521 fixed, the bot is now being triggered, but it is failing with:
```
2025-04-22 09:20:41.000225 [WARNING ] [warning  ] Backend rejected the payload: b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n'
2025-04-22 09:20:41.000301 [ERROR   ] [error    ] Static analysis failure        error=AssertionError('Stopping early because revision could not be created nor retrieved from the backend') revision=PHID-DIFF-xtvjquyply5arpozjnfk
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/code_review_bot-1.10.1-py3.13.egg/code_review_bot/cli.py", line 212, in main
    w.run(revision)
    ~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/code_review_bot-1.10.1-py3.13.egg/code_review_bot/workflow.py", line 111, in run
    issues, task_failures, notices, reviewers = self.find_issues(
                                                ~~~~~~~~~~~~~~~~^
        revision, settings.try_group_id
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/code_review_bot-1.10.1-py3.13.egg/code_review_bot/workflow.py", line 531, in find_issues
    rev is not None
AssertionError: Stopping early because revision could not be created nor retrieved from the backend
```

**Comment by marco-c** [comment]
Example failing task: https://firefox-ci-tc.services.mozilla.com/tasks/WBNQPmWDRDqFRFWFySgTMg/runs/0/logs/public/logs/live.log.

**Comment by marco-c** [comment]
There was actually a problem with XXX, because `?: (dockerflow.health.W001) Unapplied migration issues.0015_remove_repository_phid_alter_repository_id'.
Now the migration has been applied and this seems to be working. For example on https://phabricator.services.mozilla.com/D247889 I see:
![Screenshot of the Phabricator build status section, showing Source Code Analysis running](https://github.com/user-attachments/assets/7458e7d1-b28a-458b-ad5f-dc48d8fd9f8b)

**Comment by coreycb** [comment]
Thanks Marco! Confirmed comments are working for eslint https://phabricator.services.mozilla.com/D248429
